name: filmguru
description: Netguru Flutter recruitment app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  freezed: ^3.0.4
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  dartz: ^0.10.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  build_test: ^2.2.3
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0


flutter:
  uses-material-design: true

  assets:
    - assets/mock/movies_response.json

flutter_intl:
  enabled: true
